package com.example.financemonitoring.domain

val UNDEFINED_ID: Long = 0L
val UNDEFINED_NAME = "UNDEFINED_NAME"
val UNDEFINED_CHANGE = Long.MIN_VALUE
val UNDEFINED_CATEGORY = "UNDEFINED_CATEGORY"
val MODE_UNDEF = "UNDEFINED_MODE"
val EXTRA_MODE = "EXTRA_MODE"
val MODE_ADD = "MODE_ADD"
val MODE_EDIT = "MODE_EDIT"
val EXTRA_ITEM_ID = "EXTRA_ITEM_ID"