package com.example.financemonitoring.domain

val UNDEFINED_ID: Long = 0L
val UNDEFINED_CHANGE = Long.MIN_VALUE
val UNDEFINED_CATEGORY = "UNDEFINED_CATEGORY"
val MODE_UNDEF = "UNDEFINED_MODE"
val EXTRA_MODE = "EXTRA_MODE"
val MODE_ADD = "MODE_ADD"
val MODE_EDIT = "MODE_EDIT"
val EXTRA_ITEM_ID = "EXTRA_ITEM_ID"

val CATEGORY_TYPE = "CATEGORY"
val UNDEFINED_TYPE = "UNDEFINED"

val EXTRA_CATEGORIES = "EXTRA_CATEGORIES"
val EXTRA_FROM_DATE = "EXTRA_FROM_DATE"
val EXTRA_TO_DATE = "EXTRA_TO_DATE"